### ISSUE TITLE
Compatability with cython

### ISSUE THREAD

**Issue by mkenne15** [HiPERCAM/trm-pgplot#4]
I'm working on a fresh install of all the packages, and encountered the following issue. For the most recent version of cython, I think `np.int_t` has been deprecated. I replaced this with `np.int32_t` on line 11 of `_pgplot.pyx` and everything compiled. Happy to issue a pull request if you want.

**Comment by StuartLittlefair** [comment]
Thanks @mkenne15 

I just pushed a fix and then saw this issue!
